services:
  nix-dev:
    image: nixos/nix:latest
    container_name: nvim-nix-lab
    volumes:
      - nix-store:/nix
      - .:/src
    working_dir: /src
    tty: true
    stdin_open: true
    environment:
      - NIX_CONFIG=experimental-features = nix-command flakes
      - USER=root
volumes:
  nix-store:
